# Generated by Django 4.2.1 on 2023-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('state', models.CharField(max_length=64)),
                ('index', models.DecimalField(decimal_places=1, max_digits=5)),
                ('grocery', models.DecimalField(decimal_places=1, max_digits=5)),
                ('housing', models.DecimalField(decimal_places=1, max_digits=5)),
                ('utilities', models.DecimalField(decimal_places=1, max_digits=5)),
                ('transportation', models.DecimalField(decimal_places=1, max_digits=5)),
                ('health', models.DecimalField(decimal_places=1, max_digits=5)),
                ('misc', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
