# Generated by Django 4.2.1 on 2023-05-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='col',
            name='state_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
