# Generated by Django 4.2.1 on 2023-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(max_length=64)),
                ('industry', models.CharField(max_length=128)),
                ('job_function', models.CharField(max_length=128)),
                ('senority', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=64)),
                ('education', models.CharField(max_length=64)),
                ('months_experience', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salary_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(max_length=64)),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
            ],
        ),
    ]
