# Generated by Django 4.2.1 on 2023-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0002_alter_job_education_alter_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
