# Generated by Django 4.2.1 on 2023-05-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0003_alter_job_lat_alter_job_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
