# Generated by Django 4.2.1 on 2023-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0004_alter_job_lat_alter_job_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
