# Generated by Django 4.2.1 on 2023-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_user_profile_saved_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='desired_location',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='skills',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
